/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-04-09 09:14:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Map;
import core.SessionManage;
import controller.MedicalController;
import modal.MedicalTest;
import java.util.List;

public final class appoiment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(5);
    _jspx_imports_classes.add("core.SessionManage");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("modal.MedicalTest");
    _jspx_imports_classes.add("controller.MedicalController");
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    	");

		String userEmail = (String) session.getAttribute("user-email");
		String userFirstName = (String) session.getAttribute("user-first-name");
		String userRole = (String) session.getAttribute("user-role");
		
      out.write("\r\n");
      out.write("		");

		if(session.getAttribute("user-email") == null){
			response.sendRedirect("login.jsp");
		}

	
	Map<String, String> fieldErrors = (Map<String, String>) session.getAttribute("fieldErrors");
	String bookingDateError = SessionManage.getFiledValue(fieldErrors, "booking_date");
	String bookingTimeError = SessionManage.getFiledValue(fieldErrors, "booking_time");
	String medicalTestError = SessionManage.getFiledValue(fieldErrors, "medical_test");
	String recommendedDoctorError = SessionManage.getFiledValue(fieldErrors, "recommended_doctor");
	session.removeAttribute("fieldErrors");
	
	String status = (String) session.getAttribute("user-create-status");
	session.removeAttribute("user-create-status");
	if (status != null) {
		session.removeAttribute("createUserFileds");
	}
	
	String booking_date, booking_time, recommended_doctor;
	booking_date = booking_time = recommended_doctor = "";
	Map<String, String> inputs = (Map<String, String>) session.getAttribute("createUserFileds");
	booking_date = SessionManage.getFiledValue(inputs, "booking_date");
	booking_time = SessionManage.getFiledValue(inputs, "booking_time");
	recommended_doctor = SessionManage.getFiledValue(inputs, "recommended_doctor");
	session.removeAttribute("createUserFileds");
	
	List<MedicalTest> medicalTestList = MedicalController.getAllActiveMedicalTest();
	
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("  <meta name=\"description\" content=\"Orbitor,business,company,agency,modern,bootstrap4,tech,software\">\r\n");
      out.write("  <meta name=\"author\" content=\"themefisher.com\">\r\n");
      out.write("  <title>ABC Laboratories</title>\r\n");
      out.write("  <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"./front-end/images/favicon.png\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./front-end/plugins/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css'>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./front-end/plugins/icofont/icofont.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./front-end/plugins/slick-carousel/slick/slick.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./front-end/plugins/slick-carousel/slick/slick-theme.css\"> \r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./front-end/css/style.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./front-end/css/payment.css\"> \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"top\">\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("	<div class=\"header-top-bar\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row align-items-center\">\r\n");
      out.write("				<div class=\"col-lg-6\">\r\n");
      out.write("					<ul class=\"top-bar-info list-inline-item pl-0 mb-0\">\r\n");
      out.write("						<li class=\"list-inline-item\"><a href=\"mailto:abclaboratories@email.com\"><i class=\"icofont-support-faq mr-2\"></i>abclaboratories@email.com</a></li>\r\n");
      out.write("						<li class=\"list-inline-item\"><i class=\"icofont-location-pin mr-2\"></i>Address Kururnegala, Sri Lanka </li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-6\">\r\n");
      out.write("                    <div class=\"text-right top-right-bar mt-2 mt-lg-0\">\r\n");
      out.write("						");

						if (userFirstName == null || userEmail == null) {
						
      out.write("\r\n");
      out.write("						<a href=\"registration.jsp\" class=\"btn btn-outline-light btn-solid-white\">Register</a>\r\n");
      out.write("						<a href=\"login.jsp\" class=\"btn btn-outline-light btn-solid-white\">Log In</a>\r\n");
      out.write("						");

						} else {
						
      out.write("\r\n");
      out.write("						<a class=\"\"  id=\"dropdown03\" data-toggle=\"dropdown\">\r\n");
      out.write("                             Hi, ");
      out.print( userFirstName );
      out.write(" <i class=\"icofont-thin-down\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"dropdown-menu mt-3\" aria-labelledby=\"dropdown03\">\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"dashbord.jsp\">Manage Appointment</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"logout\">Log Out</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navigation\" id=\"navbar\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("		 	 <a class=\"navbar-brand\" href=\"index.jsp\">\r\n");
      out.write("			  	<img src=\"./front-end/images/logo.png\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("			  </a>\r\n");
      out.write("\r\n");
      out.write("		  	<button class=\"navbar-toggler collapsed\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarmain\" aria-controls=\"navbarmain\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("			<span class=\"icofont-navigation-menu\"></span>\r\n");
      out.write("		  </button>\r\n");
      out.write("	  \r\n");
      out.write("		  <div class=\"collapse navbar-collapse\" id=\"navbarmain\">\r\n");
      out.write("			<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.jsp\">Home</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"service.jsp\">Services</a></li>\r\n");
      out.write("				<li class=\"nav-item active\"><a class=\"nav-link\" href=\"contact.jsp\">Contact</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"appoiment.jsp\">Make appoinment </a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		  </div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("</header>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"page-title bg-1\">\r\n");
      out.write("  <div class=\"overlay\"></div>\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-md-12\">\r\n");
      out.write("        <div class=\"block text-center\">\r\n");
      out.write("          <span class=\"text-white\">Make Appoinment</span>\r\n");
      out.write("          <h1 class=\"text-capitalize mb-5 text-lg\">Appoinment</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section class=\"contact-form-wrap section\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row justify-content-center\">\r\n");
      out.write("            <div class=\"col-lg-10\">\r\n");
      out.write("                <div class=\"section-title text-center\">\r\n");
      out.write("                    <h2 class=\"text-md mb-2\">Schedule Your Appoinment</h2>\r\n");
      out.write("                    <div class=\"divider mx-auto my-4\"></div>\r\n");
      out.write("                    <p class=\"mb-5\">Welcome to our appointment scheduling portal! We're thrilled that you've chosen to book with us. Please fill out the form below to secure your appointment slot. If you have any questions or need assistance, don't hesitate to reach out to our team. We look forward to serving you soon!</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"border col-lg-8 col-md-12 col-sm-12 mx-auto p-lg-5 rounded\">\r\n");
      out.write("				<form id=\"#\" class=\"appoinment-form\" method=\"post\" action=\"AppoimentServlet\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-lg-6\">\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"medical_test\">Select Medical Test</label>\r\n");
      out.write("								<select class=\"form-control\" id=\"medical_test\" name=\"medical_test\" onchange=\"updateDetails()\">\r\n");
      out.write("									");

									for (MedicalTest medicalTest : medicalTestList) {
									
      out.write("\r\n");
      out.write("									<option value=\"");
      out.print(medicalTest.getId());
      out.write('"');
      out.write('>');
      out.print(medicalTest.getName());
      out.write("</option>\r\n");
      out.write("									");

									}
									
      out.write("\r\n");
      out.write("								</select>\r\n");
      out.write("								");
      out.print((medicalTestError != null) ? "<span class=\"text-danger\">" + medicalTestError + "</span>" : "");
      out.write("\r\n");
      out.write("							  </div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-6\">\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"booking_time\">Booking time</label>\r\n");
      out.write("								<select class=\"form-control\" id=\"booking_time\" name=\"booking_time\">\r\n");
      out.write("									<option value=\"\">Select Booking Time</option>\r\n");
      out.write("									<option value=\"08:00\">08:30</option>\r\n");
      out.write("									<option value=\"09:00\">09:00</option>\r\n");
      out.write("									<option value=\"09:30\">09:30</option>\r\n");
      out.write("									<option value=\"10:00\">10:00</option>\r\n");
      out.write("									<option value=\"10:30\">10:30</option>\r\n");
      out.write("									<option value=\"11:00\">11:00</option>\r\n");
      out.write("									<option value=\"11:30\">11:30</option>\r\n");
      out.write("									<option value=\"12:00\">12:00</option>\r\n");
      out.write("									<option value=\"12:30\">12:30</option>\r\n");
      out.write("									<option value=\"13:00\">13:00</option>\r\n");
      out.write("									<option value=\"13:30\">13:30</option>\r\n");
      out.write("									<option value=\"14:00\">14:00</option>\r\n");
      out.write("									<option value=\"14:30\">14:30</option>\r\n");
      out.write("									<option value=\"15:00\">15:00</option>\r\n");
      out.write("									<option value=\"15:30\">15:30</option>\r\n");
      out.write("									<option value=\"16:00\">16:00</option>\r\n");
      out.write("									<option value=\"16:30\">16:30</option>\r\n");
      out.write("									<option value=\"17:00\">17:00</option>\r\n");
      out.write("									<option value=\"17:30\">17:30</option>\r\n");
      out.write("									<option value=\"18:00\">18:00</option>\r\n");
      out.write("								</select>\r\n");
      out.write("								");
      out.print((bookingTimeError != null) ? "<span class=\"text-danger\">" + bookingTimeError + "</span>" : "");
      out.write("\r\n");
      out.write("							  </div>\r\n");
      out.write("						</div>\r\n");
      out.write("<div class=\"col-lg-6\">\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("        <label for=\"booking_date\">Booking Date</label>\r\n");
      out.write("        <input type=\"date\" class=\"form-control\" id=\"booking_date\" name=\"booking_date\" placeholder=\"booking date\" value=\"");
      out.print(booking_date);
      out.write("\" min=\"");
      out.print(java.time.LocalDate.now());
      out.write("\">\r\n");
      out.write("        ");
      out.print((bookingDateError != null) ? "<span class=\"text-danger\">" + bookingDateError + "</span>" : "");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("				\r\n");
      out.write("						<div class=\"col-lg-6\">\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"recommended_doctor\">Recommended Doctor</label>\r\n");
      out.write("								<input type=\"text\" class=\"form-control\" id=\"recommended_doctor\" name=\"recommended_doctor\" placeholder=\"Recommended Doctor Name\" value=\"");
      out.print(recommended_doctor);
      out.write("\">\r\n");
      out.write("								");
      out.print((recommendedDoctorError != null) ? "<span class=\"text-danger\">" + recommendedDoctorError + "</span>" : "");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"text-center makeappoinment\">\r\n");
      out.write("						<button class=\"btn btn-main btn-round-full\" type=\"submit\">Make Appoinment <i class=\"icofont-simple-right ml-2\"></i></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("					<div class=\"form-check form-switch mb-2\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"flexSwitchCheckDefault\" />\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"flexSwitchCheckDefault\"\r\n");
      out.write("                          >Card Payment</label\r\n");
      out.write("                        >\r\n");
      out.write("                    </div>\r\n");
      out.write("					<div class=\"hide hidden-element\">\r\n");
      out.write("						  <div class=\"card-data flex-fill flex-vertical\">\r\n");
      out.write("							<div class=\"flex-between flex-vertical-center\">\r\n");
      out.write("							  <div class=\"card-property-title\">\r\n");
      out.write("								<strong>Card Number</strong>\r\n");
      out.write("								<span>Enter 16-digit card number on the card</span>\r\n");
      out.write("							  </div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"flex-between\">\r\n");
      out.write("							  <div class=\"card-number flex-vertical-center flex-fill\">\r\n");
      out.write("								<div class=\"card-number-field flex-vertical-center flex-fill\">\r\n");
      out.write("								  <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 48 48\" width=\"24px\" height=\"24px\">\r\n");
      out.write("									<path fill=\"#ff9800\" d=\"M32 10A14 14 0 1 0 32 38A14 14 0 1 0 32 10Z\" />\r\n");
      out.write("									<path fill=\"#d50000\" d=\"M16 10A14 14 0 1 0 16 38A14 14 0 1 0 16 10Z\" />\r\n");
      out.write("									<path fill=\"#ff3d00\" d=\"M18,24c0,4.755,2.376,8.95,6,11.48c3.624-2.53,6-6.725,6-11.48s-2.376-8.95-6-11.48 C20.376,15.05,18,19.245,18,24z\" />\r\n");
      out.write("								  </svg>\r\n");
      out.write("								  <input type=\"text\" placeholder=\"Card Number\" class=\"form-control\" id=\"cardNumber\" onkeypress=\"return onlyNumberKey(event)\" maxlength=\"19\" name=\"cardNumber\" data-bound=\"carddigits_mock\" data-def=\"0000 0000 0000 0000\"/>\r\n");
      out.write("								</div>\r\n");
      out.write("								<i class=\"ai-circle-check-fill size-lg f-main-color\"></i>\r\n");
      out.write("							  </div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"flex-between\">\r\n");
      out.write("							  <div class=\"card-property-title\">\r\n");
      out.write("								<strong>Expiry Date</strong>\r\n");
      out.write("								<span>Enter the expiration date of the card</span>\r\n");
      out.write("							  </div>\r\n");
      out.write("							  <div class=\"card-property-value flex-vertical-center\">\r\n");
      out.write("								<div class=\"input-container half-width\">\r\n");
      out.write("								  <input class=\"numbers month-own\" data-def=\"00\" type=\"text\" data-bound=\"mm_mock\" placeholder=\"MM\" />\r\n");
      out.write("								</div>\r\n");
      out.write("								<span class=\"m-md\">/</span>\r\n");
      out.write("								<div class=\"input-container half-width\">\r\n");
      out.write("								  <input class=\"numbers year-own\" data-def=\"01\" type=\"text\" data-bound=\"yy_mock\" placeholder=\"YYYY\" />\r\n");
      out.write("								</div>\r\n");
      out.write("							  </div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"flex-between\">\r\n");
      out.write("							  <div class=\"card-property-title\">\r\n");
      out.write("								<strong>CVC Number</strong>\r\n");
      out.write("								<span>Enter card verification code from the back of the\r\n");
      out.write("								  card</span>\r\n");
      out.write("							  </div>\r\n");
      out.write("							  <div class=\"card-property-value\">\r\n");
      out.write("								<div class=\"input-container\">\r\n");
      out.write("								  <input id=\"cvc\" placeholder=\"Card CVV\" maxlength=\"3\" onkeypress=\"return onlyNumberKey(event)\" type=\"password\" />\r\n");
      out.write("								  <i id=\"cvc_toggler\" data-target=\"cvc\" class=\"ai-eye-open pointer\"></i>\r\n");
      out.write("								</div>\r\n");
      out.write("							  </div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"flex-between\">\r\n");
      out.write("							  <div class=\"card-property-title\">\r\n");
      out.write("								<strong>Cardholder Name</strong>\r\n");
      out.write("								<span>Enter cardholder's name</span>\r\n");
      out.write("							  </div>\r\n");
      out.write("							  <div class=\"card-property-value\">\r\n");
      out.write("								<div class=\"input-container\">\r\n");
      out.write("								  <input id=\"name\" data-bound=\"name_mock\" data-def=\"Mr. Cardholder\" type=\"text\" class=\"uppercase\" placeholder=\"CARDHOLDER NAME\" />\r\n");
      out.write("								  <i class=\"ai-person\"></i>\r\n");
      out.write("								</div>\r\n");
      out.write("							  </div>\r\n");
      out.write("							</div>\r\n");
      out.write("						  </div>\r\n");
      out.write("						  <div class=\"action flex-center\">\r\n");
      out.write("							<button type=\"\" class=\"b-main-color pointer\">\r\n");
      out.write("							  Pay Now\r\n");
      out.write("							</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</form>\r\n");
      out.write("            </div>\r\n");
      out.write("			<div class=\"col-lg-4 col-md-12 py-5 pay hidden-element\">\r\n");
      out.write("				<div></div>\r\n");
      out.write("				<div class=\"purchase-section flex-fill flex-vertical\">\r\n");
      out.write("				  <div class=\"card-mockup flex-vertical\">\r\n");
      out.write("					<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 48 48\" width=\"40px\" height=\"40px\">\r\n");
      out.write("					  <path fill=\"#ff9800\" d=\"M32 10A14 14 0 1 0 32 38A14 14 0 1 0 32 10Z\" />\r\n");
      out.write("					  <path fill=\"#d50000\" d=\"M16 10A14 14 0 1 0 16 38A14 14 0 1 0 16 10Z\" />\r\n");
      out.write("					  <path fill=\"#ff3d00\" d=\"M18,24c0,4.755,2.376,8.95,6,11.48c3.624-2.53,6-6.725,6-11.48s-2.376-8.95-6-11.48 C20.376,15.05,18,19.245,18,24z\" />\r\n");
      out.write("					</svg>\r\n");
      out.write("					<div>\r\n");
      out.write("					  <strong>\r\n");
      out.write("						<div id=\"name_mock\" class=\"size-md pb-sm uppercase ellipsis\">\r\n");
      out.write("						  mr. Cardholder\r\n");
      out.write("						</div>\r\n");
      out.write("					  </strong>\r\n");
      out.write("					  <div class=\"size-md pb-md\">\r\n");
      out.write("						<strong>\r\n");
      out.write("						  <span id=\"carddigits_mock\">0000 0000 0000 0000</span>\r\n");
      out.write("						</strong>\r\n");
      out.write("					  </div>\r\n");
      out.write("					  <div class=\"flex-between flex-vertical-center\">\r\n");
      out.write("						<strong class=\"size-md\">\r\n");
      out.write("						  <span>Expiry Date : </span><span id=\"mm_mock\">00</span> / <span id=\"yy_mock\">00</span>\r\n");
      out.write("						</strong>\r\n");
      out.write("	  \r\n");
      out.write("						<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 48 48\" width=\"40px\" height=\"40px\">\r\n");
      out.write("						  <path fill=\"#1565C0\" d=\"M45,35c0,2.209-1.791,4-4,4H7c-2.209,0-4-1.791-4-4V13c0-2.209,1.791-4,4-4h34c2.209,0,4,1.791,4,4V35z\" />\r\n");
      out.write("						  <path fill=\"#FFF\" d=\"M15.186 19l-2.626 7.832c0 0-.667-3.313-.733-3.729-1.495-3.411-3.701-3.221-3.701-3.221L10.726 30v-.002h3.161L18.258 19H15.186zM17.689 30L20.56 30 22.296 19 19.389 19zM38.008 19h-3.021l-4.71 11h2.852l.588-1.571h3.596L37.619 30h2.613L38.008 19zM34.513 26.328l1.563-4.157.818 4.157H34.513zM26.369 22.206c0-.606.498-1.057 1.926-1.057.928 0 1.991.674 1.991.674l.466-2.309c0 0-1.358-.515-2.691-.515-3.019 0-4.576 1.444-4.576 3.272 0 3.306 3.979 2.853 3.979 4.551 0 .291-.231.964-1.888.964-1.662 0-2.759-.609-2.759-.609l-.495 2.216c0 0 1.063.606 3.117.606 2.059 0 4.915-1.54 4.915-3.752C30.354 23.586 26.369 23.394 26.369 22.206z\" />\r\n");
      out.write("						  <path fill=\"#FFC107\" d=\"M12.212,24.945l-0.966-4.748c0,0-0.437-1.029-1.573-1.029c-1.136,0-4.44,0-4.44,0S10.894,20.84,12.212,24.945z\" />\r\n");
      out.write("						</svg>\r\n");
      out.write("					  </div>\r\n");
      out.write("					</div>\r\n");
      out.write("				  </div>\r\n");
      out.write("	  \r\n");
      out.write("				  <ul class=\"purchase-props\">\r\n");
      out.write("					<li class=\"flex-between\">\r\n");
      out.write("					  <span>Company</span>\r\n");
      out.write("					  <strong>ABC Laboratories</strong>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"flex-between\">\r\n");
      out.write("					  <span>Test </span>\r\n");
      out.write("					  <strong id=\"testname\">N/A</strong>\r\n");
      out.write("					</li>\r\n");
      out.write("				  </ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"separation-line\"></div>\r\n");
      out.write("				<div class=\"total-section flex-between flex-vertical-center\">\r\n");
      out.write("				  <div class=\"flex-fill flex-vertical\">\r\n");
      out.write("					<div class=\"total-label f-secondary-color\">You have to Pay</div>\r\n");
      out.write("					<div>\r\n");
      out.write("					  <strong id=\"valuess\">00</strong>\r\n");
      out.write("					  <small>.00 <span class=\"f-secondary-color\">LKR</span></small>\r\n");
      out.write("					</div>\r\n");
      out.write("				  </div>\r\n");
      out.write("				  <i class=\"ai-coin size-lg\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("			  </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"footer section\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-lg-4 mr-auto col-sm-6\">\r\n");
      out.write("				<div class=\"widget mb-5 mb-lg-0\">\r\n");
      out.write("					<div class=\"logo mb-4\">\r\n");
      out.write("						<img src=\"./front-end/images/logo1.png\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<p>Welcome to our online appointment booking system! Whether you're a returning patient or new to our services, scheduling your appointments is quick and easy.</p>\r\n");
      out.write("\r\n");
      out.write("					<ul class=\"list-inline footer-socials mt-4\">\r\n");
      out.write("						<li class=\"list-inline-item\"><a href=\"#\"><i class=\"icofont-facebook\"></i></a></li>\r\n");
      out.write("						<li class=\"list-inline-item\"><a href=\"#\"><i class=\"icofont-twitter\"></i></a></li>\r\n");
      out.write("						<li class=\"list-inline-item\"><a href=\"#\"><i class=\"icofont-linkedin\"></i></a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-lg-4 col-md-6 col-sm-6\">\r\n");
      out.write("				<div class=\"widget mb-5 mb-lg-0\">\r\n");
      out.write("					<h4 class=\"text-capitalize mb-3\">Quick Links</h4>\r\n");
      out.write("					<div class=\"divider mb-4\"></div>\r\n");
      out.write("\r\n");
      out.write("					<ul class=\"list-unstyled footer-menu lh-35\">\r\n");
      out.write("						<li><a href=\"index.jsp\">Home </a></li>\r\n");
      out.write("						<li><a href=\"service.jsp\">Services</a></li>\r\n");
      out.write("						<li><a href=\"contact.jsp\">Contact</a></li>\r\n");
      out.write("						<li><a href=\"appoiment.jsp\">Make Appoinment</a></li>\r\n");
      out.write("						<li><a href=\"login.jsp\">Login</a></li>\r\n");
      out.write("						<li><a href=\"registration.jsp\">Register</a></li>\r\n");
      out.write("						<li><a href=\"dashbord.jsp\">Manage Appoinment</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-lg-4 col-md-6 col-sm-6\">\r\n");
      out.write("				<div class=\"widget widget-contact mb-5 mb-lg-0\">\r\n");
      out.write("					<h4 class=\"text-capitalize mb-3\">Get in Touch</h4>\r\n");
      out.write("					<div class=\"divider mb-4\"></div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"footer-contact-block mb-4\">\r\n");
      out.write("						<div class=\"icon d-flex align-items-center\">\r\n");
      out.write("							<i class=\"icofont-email mr-3\"></i>\r\n");
      out.write("							<span class=\"h6 mb-0\">Support Available for 24/7</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<h4 class=\"mt-2\"><a href=\"tel:+23-345-67890\">abclaboratories@email.com</a></h4>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"footer-contact-block\">\r\n");
      out.write("						<div class=\"icon d-flex align-items-center\">\r\n");
      out.write("							<i class=\"icofont-support mr-3\"></i>\r\n");
      out.write("							<span class=\"h6 mb-0\">Mon to Fri : 08:30 - 18:00</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<h4 class=\"mt-2\"><a href=\"tel:+23-345-67890\">+45-0456-6588</a></h4>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"footer-btm py-4 mt-5\">\r\n");
      out.write("			<div class=\"row align-items-center justify-content-between\">\r\n");
      out.write("				<div class=\"col-lg-6\">\r\n");
      out.write("					<div class=\"copyright\">\r\n");
      out.write("						&copy; Copyright Reserved to <span class=\"text-color\">ABC Laboratories</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-4\">\r\n");
      out.write("					<a class=\"backtop js-scroll-trigger\" href=\"#top\">\r\n");
      out.write("						<i class=\"icofont-long-arrow-up\"></i>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    <script src=\"./front-end/plugins/jquery/jquery.js\"></script>\r\n");
      out.write("    <script src=\"./front-end/plugins/bootstrap/js/popper.js\"></script>\r\n");
      out.write("    <script src=\"./front-end/plugins/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"./front-end/plugins/counterup/jquery.easing.js\"></script>\r\n");
      out.write("    <script src=\"./front-end/plugins/slick-carousel/slick/slick.min.js\"></script>\r\n");
      out.write("    <script src=\"./front-end/plugins/counterup/jquery.waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"./front-end/plugins/shuffle/shuffle.min.js\"></script>\r\n");
      out.write("    <script src=\"./front-end/plugins/counterup/jquery.counterup.min.js\"></script>\r\n");
      out.write("    <script src=\"./front-end/plugins/google-map/map.js\"></script>\r\n");
      out.write("	<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js'></script>\r\n");
      out.write("	<script src='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js'></script>  \r\n");
      out.write("    <script src=\"./front-end/js/script.js\"></script>\r\n");
      out.write("    	<script src=\"./front-end/js/payment.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
