/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-04-09 09:13:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('	');

String userEmail = (String) session.getAttribute("user-email");
String userFirstName = (String) session.getAttribute("user-first-name");
String userRole = (String) session.getAttribute("user-role");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("  <title>ABC Laboratories</title>\r\n");
      out.write("  <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"./front-end/images/favicon.png\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./front-end/plugins/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./front-end/plugins/icofont/icofont.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./front-end/plugins/slick-carousel/slick/slick.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./front-end/plugins/slick-carousel/slick/slick-theme.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./front-end/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"top\">\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("	<div class=\"header-top-bar\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row align-items-center\">\r\n");
      out.write("				<div class=\"col-lg-6\">\r\n");
      out.write("					<ul class=\"top-bar-info list-inline-item pl-0 mb-0\">\r\n");
      out.write("						<li class=\"list-inline-item\"><a href=\"mailto:abclaboratories@email.com\"><i class=\"icofont-support-faq mr-2\"></i>abclaboratories@email.com</a></li>\r\n");
      out.write("						<li class=\"list-inline-item\"><i class=\"icofont-location-pin mr-2\"></i>Address Kururnegala, Sri Lanka </li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-6\">\r\n");
      out.write("                    <div class=\"text-right top-right-bar mt-2 mt-lg-0\">\r\n");
      out.write("						");

						if (userFirstName == null || userEmail == null) {
						
      out.write("\r\n");
      out.write("						<a href=\"registration.jsp\" class=\"btn btn-outline-light btn-solid-white\">Register</a>\r\n");
      out.write("						<a href=\"login.jsp\" class=\"btn btn-outline-light btn-solid-white\">Log In</a>\r\n");
      out.write("						");

						} else {
						
      out.write("\r\n");
      out.write("						<a class=\"\"  id=\"dropdown03\" data-toggle=\"dropdown\">\r\n");
      out.write("                             Hi, ");
      out.print( userFirstName );
      out.write(" <i class=\"icofont-thin-down\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"dropdown-menu mt-3\" aria-labelledby=\"dropdown03\">\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"dashbord.jsp\">Manage Appointment</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"logout\">Log Out</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navigation\" id=\"navbar\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("		 	 <a class=\"navbar-brand\" href=\"index.jsp\">\r\n");
      out.write("			  	<img src=\"./front-end/images/logo.png\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("			  </a>\r\n");
      out.write("\r\n");
      out.write("		  	<button class=\"navbar-toggler collapsed\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarmain\" aria-controls=\"navbarmain\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("			<span class=\"icofont-navigation-menu\"></span>\r\n");
      out.write("		  </button>\r\n");
      out.write("	  \r\n");
      out.write("		  <div class=\"collapse navbar-collapse\" id=\"navbarmain\">\r\n");
      out.write("			<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("				<li class=\"nav-item active\"><a class=\"nav-link\" href=\"index.jsp\">Home</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"service.jsp\">Services</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"contact.jsp\">Contact</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"appoiment.jsp\">Make appoinment </a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		  </div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("</header>\r\n");
      out.write("	\r\n");
      out.write("<section class=\"banner\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-lg-6 col-md-12 col-xl-7\">\r\n");
      out.write("				<div class=\"block\">\r\n");
      out.write("					<div class=\"divider mb-3\"></div>\r\n");
      out.write("					<span class=\"text-uppercase text-sm letter-spacing \">TOTAL MEDICAL TESTING SOLUTIONS</span>\r\n");
      out.write("					<h1 class=\"mb-3 mt-3\">Your Most Trusted Medical Testing Partner</h1>\r\n");
      out.write("					\r\n");
      out.write("					<p class=\"mb-4 pr-5\">A repudiandae ipsam labore ipsa voluptatum quidem quae laudantium quisquam aperiam maiores sunt fugit, deserunt rem suscipit placeat.</p>\r\n");
      out.write("					<div class=\"btn-container \">\r\n");
      out.write("						<a href=\"appoiment.jsp\" target=\"_blank\" class=\"btn btn-main-2 btn-icon btn-round-full\">Make appoinment <i class=\"icofont-simple-right ml-2  \"></i></a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("<section class=\"features\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-lg-12\">\r\n");
      out.write("				<div class=\"feature-block d-lg-flex\">\r\n");
      out.write("					<div class=\"feature-item mb-5 mb-lg-0\">\r\n");
      out.write("						<div class=\"feature-icon mb-4\">\r\n");
      out.write("							<i class=\"icofont-surgeon-alt\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("						<span>24 Hours Service</span>\r\n");
      out.write("						<h4 class=\"mb-3\">Online Appoinment</h4>\r\n");
      out.write("						<p class=\"mb-4\">Get ALl time support for emergency.We have introduced the principle of family medicine.</p>\r\n");
      out.write("						<a href=\"appoiment.jsp\" class=\"btn btn-main btn-round-full\">Make a appoinment</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				\r\n");
      out.write("					<div class=\"feature-item mb-5 mb-lg-0\">\r\n");
      out.write("						<div class=\"feature-icon mb-4\">\r\n");
      out.write("							<i class=\"icofont-ui-clock\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("						<span>Timing schedule</span>\r\n");
      out.write("						<h4 class=\"mb-3\">Working Hours</h4>\r\n");
      out.write("						<ul class=\"w-hours list-unstyled\">\r\n");
      out.write("		                    <li class=\"d-flex justify-content-between\">Sun - Wed : <span>8:00 - 17:00</span></li>\r\n");
      out.write("		                    <li class=\"d-flex justify-content-between\">Thu - Fri : <span>9:00 - 17:00</span></li>\r\n");
      out.write("		                    <li class=\"d-flex justify-content-between\">Sat - sun : <span>10:00 - 17:00</span></li>\r\n");
      out.write("		                </ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				\r\n");
      out.write("					<div class=\"feature-item mb-5 mb-lg-0\">\r\n");
      out.write("						<div class=\"feature-icon mb-4\">\r\n");
      out.write("							<i class=\"icofont-support\"></i>\r\n");
      out.write("						</div>\r\n");
      out.write("						<span>Emegency Cases</span>\r\n");
      out.write("						<h4 class=\"mb-3\">1-800-700-6200</h4>\r\n");
      out.write("						<p>Get All-time Support for Emergencies. We have introduced the principle of laboratory medicine. Connect with us for any urgent needs.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"section about\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row align-items-center\">\r\n");
      out.write("			<div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("				<div class=\"about-img\">\r\n");
      out.write("					<img src=\"./front-end/images/about/img-1.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("					<img src=\"./front-end/images/about/img-2.jpg\" alt=\"\" class=\"img-fluid mt-4\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("				<div class=\"about-img mt-4 mt-lg-0\">\r\n");
      out.write("					<img src=\"./front-end/images/about/img-3.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-lg-4\">\r\n");
      out.write("				<div class=\"about-content pl-4 mt-4 mt-lg-0\">\r\n");
      out.write("					<h2 class=\"title-color\">Personalized Care <br>& Wellness Services</h2>\r\n");
      out.write("					<p class=\"mt-4 mb-5\">We provide cutting-edge laboratory services. Nulla perferendis veniam deleniti ipsum officia dolores repellat laudantium obcaecati neque.</p>\r\n");
      out.write("\r\n");
      out.write("					<a href=\"appoiment.jsp\" class=\"btn btn-main-2 btn-round-full btn-icon\">Make a appoinment<i class=\"icofont-simple-right ml-3\"></i></a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("<section class=\"cta-section \">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"cta position-relative\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("					<div class=\"counter-stat\">\r\n");
      out.write("						<i class=\"icofont-doctor\"></i>\r\n");
      out.write("						<span class=\"h3\">58</span>k\r\n");
      out.write("						<p>Satisfied Clients</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("					<div class=\"counter-stat\">\r\n");
      out.write("						<i class=\"icofont-flag\"></i>\r\n");
      out.write("						<span class=\"h3\">700</span>+\r\n");
      out.write("						<p>Testing Completed</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("					<div class=\"counter-stat\">\r\n");
      out.write("						<i class=\"icofont-badge\"></i>\r\n");
      out.write("						<span class=\"h3\">40</span>+\r\n");
      out.write("						<p>Proficient Technicians</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("					<div class=\"counter-stat\">\r\n");
      out.write("						<i class=\"icofont-globe\"></i>\r\n");
      out.write("						<span class=\"h3\">20</span>\r\n");
      out.write("						<p>Global Presence</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("<section class=\"section service gray-bg\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row justify-content-center\">\r\n");
      out.write("			<div class=\"col-lg-7 text-center\">\r\n");
      out.write("				<div class=\"section-title\">\r\n");
      out.write("					<h2>Award-Winning Patient Services</h2>\r\n");
      out.write("					<div class=\"divider mx-auto my-4\"></div>\r\n");
      out.write("					<p>Let's learn more about the essential needs and desires; we can provide excellent care. Maiores porro cumque quaerat.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-lg-4 col-md-6 col-sm-6\">\r\n");
      out.write("				<div class=\"service-item mb-4\">\r\n");
      out.write("					<div class=\"icon d-flex align-items-center\">\r\n");
      out.write("						<i class=\"icofont-laboratory text-lg\"></i>\r\n");
      out.write("						<h4 class=\"mt-3 mb-3\">Laboratory Testing</h4>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"content\">\r\n");
      out.write("						<p class=\"mb-4\">Accurate diagnostics for precise healthcare decisions</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-lg-4 col-md-6 col-sm-6\">\r\n");
      out.write("				<div class=\"service-item mb-4\">\r\n");
      out.write("					<div class=\"icon d-flex align-items-center\">\r\n");
      out.write("						<i class=\"icofont-heart-beat-alt text-lg\"></i>\r\n");
      out.write("						<h4 class=\"mt-3 mb-3\">Cardiovascular Health</h4>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"content\">\r\n");
      out.write("						<p class=\"mb-4\">Comprehensive care for a healthy heart and circulation.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"col-lg-4 col-md-6 col-sm-6\">\r\n");
      out.write("				<div class=\"service-item mb-4\">\r\n");
      out.write("					<div class=\"icon d-flex align-items-center\">\r\n");
      out.write("						<i class=\"icofont-tooth text-lg\"></i>\r\n");
      out.write("						<h4 class=\"mt-3 mb-3\">Oral Health</h4>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"content\">\r\n");
      out.write("						<p class=\"mb-4\">Quality dental services for a radiant smile and optimal dental wellness.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-lg-4 col-md-6 col-sm-6\">\r\n");
      out.write("				<div class=\"service-item mb-4\">\r\n");
      out.write("					<div class=\"icon d-flex align-items-center\">\r\n");
      out.write("						<i class=\"icofont-crutch text-lg\"></i>\r\n");
      out.write("						<h4 class=\"mt-3 mb-3\">Cosmetic Procedures</h4>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"content\">\r\n");
      out.write("						<p class=\"mb-4\">Enhancing your natural beauty with safe and effective treatments.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-lg-4 col-md-6 col-sm-6\">\r\n");
      out.write("				<div class=\"service-item mb-4\">\r\n");
      out.write("					<div class=\"icon d-flex align-items-center\">\r\n");
      out.write("						<i class=\"icofont-brain-alt text-lg\"></i>\r\n");
      out.write("						<h4 class=\"mt-3 mb-3\">Neurological Health</h4>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"content\">\r\n");
      out.write("						<p class=\"mb-4\">Advanced therapies for neurological conditions, ensuring optimal brain...</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"col-lg-4 col-md-6 col-sm-6\">\r\n");
      out.write("				<div class=\"service-item mb-4\">\r\n");
      out.write("					<div class=\"icon d-flex align-items-center\">\r\n");
      out.write("						<i class=\"icofont-dna-alt-1 text-lg\"></i>\r\n");
      out.write("						<h4 class=\"mt-3 mb-3\">Women's Health</h4>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"content\">\r\n");
      out.write("						<p class=\"mb-4\">Specialized care catering to the unique needs of women throughout their lives.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("<section class=\"section appoinment\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row align-items-center\">\r\n");
      out.write("			<div class=\"col-lg-6 \">\r\n");
      out.write("				<div class=\"appoinment-content\">\r\n");
      out.write("					<img src=\"./front-end/images/about/img-3.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("					<div class=\"emergency\">\r\n");
      out.write("						<h2 class=\"text-lg\"><i class=\"icofont-phone-circle text-lg\"></i>+23 345 67980</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-lg-6 col-md-10 \">\r\n");
      out.write("				<div class=\"appoinment-wrap mt-5 mt-lg-0\">\r\n");
      out.write("					<h2 class=\"mb-2 title-color\">Book appoinment</h2>\r\n");
      out.write("					<p class=\"mb-4\">Welcome to our online appointment booking system! Whether you're a returning patient or new to our services, scheduling your appointments is quick and easy.</p>\r\n");
      out.write("                    <p class=\"mb-4\">First, log in or register to access your account. Once logged in, simply select your preferred date, time, and type of appointment.After booking, you'll receive a confirmation email with all the details. You can manage your appointments, including rescheduling or canceling, in the \"Manage Appointments\" section.</p>\r\n");
      out.write("                    <p class=\"mb-4\">At ABC Laboratories, we prioritize your time and health. Schedule your appointment today and take the first step towards better health with us.</p>\r\n");
      out.write("					<a href=\"appoiment.jsp\" class=\"btn btn-main-2 btn-round-full btn-icon\">Book appoinment<i class=\"icofont-simple-right ml-3\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("<section class=\"section testimonial-2 gray-bg\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row justify-content-center\">\r\n");
      out.write("			<div class=\"col-lg-7\">\r\n");
      out.write("				<div class=\"section-title text-center\">\r\n");
      out.write("					<h2>We've Supported 5000+ Patients</h2>\r\n");
      out.write("					<div class=\"divider mx-auto my-4\"></div>\r\n");
      out.write("					<p>Discover how we can address your needs with expertise and care. Whether it's addressing discomfort or seeking solutions, we're here to guide you.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row align-items-center\">\r\n");
      out.write("			<div class=\"col-lg-12 testimonial-wrap-2\">\r\n");
      out.write("				<div class=\"testimonial-block style-2  gray-bg\">\r\n");
      out.write("					<i class=\"icofont-quote-right\"></i>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"testimonial-thumb\">\r\n");
      out.write("						<img src=\"./front-end/images/team/test-thumb1.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"client-info \">\r\n");
      out.write("						<h4>Impressive Facility!</h4>\r\n");
      out.write("						<span>Samantha Smith</span>\r\n");
      out.write("						<p>\r\n");
      out.write("							The laboratory is top-notch with state-of-the-art equipment. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque rem, praesentium, iure, ipsum magnam deleniti a vel eos adipisci suscipit fugit placeat.\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"testimonial-block style-2  gray-bg\">\r\n");
      out.write("					<div class=\"testimonial-thumb\">\r\n");
      out.write("						<img src=\"./front-end/images/team/test-thumb2.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"client-info\">\r\n");
      out.write("						<h4>Professional Staff!</h4>\r\n");
      out.write("						<span>Michael Johnson</span>\r\n");
      out.write("						<p>\r\n");
      out.write("							The staff members are knowledgeable and courteous. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque rem, praesentium, iure, ipsum magnam deleniti a vel eos adipisci suscipit fugit placeat.\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<i class=\"icofont-quote-right\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"testimonial-block style-2  gray-bg\">\r\n");
      out.write("					<div class=\"testimonial-thumb\">\r\n");
      out.write("						<img src=\"./front-end/images/team/test-thumb3.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"client-info\">\r\n");
      out.write("						<h4>Efficient Services!</h4>\r\n");
      out.write("						<span>Emily Thompson</span>\r\n");
      out.write("						<p>\r\n");
      out.write("							I was impressed with how quickly they processed my tests. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque rem, praesentium, iure, ipsum magnam deleniti a vel eos adipisci suscipit fugit placeat.\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<i class=\"icofont-quote-right\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"testimonial-block style-2  gray-bg\">\r\n");
      out.write("					<div class=\"testimonial-thumb\">\r\n");
      out.write("						<img src=\"./front-end/images/team/test-thumb4.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"client-info\">\r\n");
      out.write("						<h4>Excellent Customer Care!</h4>\r\n");
      out.write("						<span>David Williams</span>\r\n");
      out.write("						<p>\r\n");
      out.write("							The customer service team went above and beyond to assist me with my queries. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque rem, praesentium, iure, ipsum magnam deleniti a vel eos adipisci suscipit fugit placeat.\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<i class=\"icofont-quote-right\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"testimonial-block style-2  gray-bg\">\r\n");
      out.write("					<div class=\"testimonial-thumb\">\r\n");
      out.write("						<img src=\"./front-end/images/team/test-thumb1.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"client-info\">\r\n");
      out.write("						<h4>Reliable Results!</h4>\r\n");
      out.write("						<span>Alice Brown</span>\r\n");
      out.write("						<p>\r\n");
      out.write("							I trust the accuracy of the test results provided by this laboratory. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque rem, praesentium, iure, ipsum magnam deleniti a vel eos adipisci suscipit fugit placeat.\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<i class=\"icofont-quote-right\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("<footer class=\"footer section\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-lg-4 mr-auto col-sm-6\">\r\n");
      out.write("				<div class=\"widget mb-5 mb-lg-0\">\r\n");
      out.write("					<div class=\"logo mb-4\">\r\n");
      out.write("						<img src=\"./front-end/images/logo1.png\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<p>Welcome to our online appointment booking system! Whether you're a returning patient or new to our services, scheduling your appointments is quick and easy.</p>\r\n");
      out.write("\r\n");
      out.write("					<ul class=\"list-inline footer-socials mt-4\">\r\n");
      out.write("						<li class=\"list-inline-item\"><a href=\"#\"><i class=\"icofont-facebook\"></i></a></li>\r\n");
      out.write("						<li class=\"list-inline-item\"><a href=\"#\"><i class=\"icofont-twitter\"></i></a></li>\r\n");
      out.write("						<li class=\"list-inline-item\"><a href=\"#\"><i class=\"icofont-linkedin\"></i></a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-lg-4 col-md-6 col-sm-6\">\r\n");
      out.write("				<div class=\"widget mb-5 mb-lg-0\">\r\n");
      out.write("					<h4 class=\"text-capitalize mb-3\">Quick Links</h4>\r\n");
      out.write("					<div class=\"divider mb-4\"></div>\r\n");
      out.write("\r\n");
      out.write("					<ul class=\"list-unstyled footer-menu lh-35\">\r\n");
      out.write("						<li><a href=\"index.jsp\">Home </a></li>\r\n");
      out.write("						<li><a href=\"service.jsp\">Services</a></li>\r\n");
      out.write("						<li><a href=\"contact.jsp\">Contact</a></li>\r\n");
      out.write("						<li><a href=\"appoiment.jsp\">Make Appoinment</a></li>\r\n");
      out.write("						<li><a href=\"login.jsp\">Login</a></li>\r\n");
      out.write("						<li><a href=\"registration.jsp\">Register</a></li>\r\n");
      out.write("						<li><a href=\"dashbord.jsp\">Manage Appoinment</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-lg-4 col-md-6 col-sm-6\">\r\n");
      out.write("				<div class=\"widget widget-contact mb-5 mb-lg-0\">\r\n");
      out.write("					<h4 class=\"text-capitalize mb-3\">Get in Touch</h4>\r\n");
      out.write("					<div class=\"divider mb-4\"></div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"footer-contact-block mb-4\">\r\n");
      out.write("						<div class=\"icon d-flex align-items-center\">\r\n");
      out.write("							<i class=\"icofont-email mr-3\"></i>\r\n");
      out.write("							<span class=\"h6 mb-0\">Support Available for 24/7</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<h4 class=\"mt-2\"><a href=\"tel:+23-345-67890\">abclaboratories@email.com</a></h4>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"footer-contact-block\">\r\n");
      out.write("						<div class=\"icon d-flex align-items-center\">\r\n");
      out.write("							<i class=\"icofont-support mr-3\"></i>\r\n");
      out.write("							<span class=\"h6 mb-0\">Mon to Fri : 08:30 - 18:00</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<h4 class=\"mt-2\"><a href=\"tel:+23-345-67890\">+45-0456-6588</a></h4>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"footer-btm py-4 mt-5\">\r\n");
      out.write("			<div class=\"row align-items-center justify-content-between\">\r\n");
      out.write("				<div class=\"col-lg-6\">\r\n");
      out.write("					<div class=\"copyright\">\r\n");
      out.write("						&copy; Copyright Reserved to <span class=\"text-color\">ABC Laboratories</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-4\">\r\n");
      out.write("					<a class=\"backtop js-scroll-trigger\" href=\"#top\">\r\n");
      out.write("						<i class=\"icofont-long-arrow-up\"></i>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    <script src=\"./front-end/plugins/jquery/jquery.js\"></script>\r\n");
      out.write("    <script src=\"./front-end/plugins/bootstrap/js/popper.js\"></script>\r\n");
      out.write("    <script src=\"./front-end/plugins/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"./front-end/plugins/counterup/jquery.easing.js\"></script>\r\n");
      out.write("    <script src=\"./front-end/plugins/slick-carousel/slick/slick.min.js\"></script>\r\n");
      out.write("    <script src=\"./front-end/plugins/counterup/jquery.waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"./front-end/plugins/shuffle/shuffle.min.js\"></script>\r\n");
      out.write("    <script src=\"./front-end/plugins/counterup/jquery.counterup.min.js\"></script>\r\n");
      out.write("    <script src=\"./front-end/plugins/google-map/map.js\"></script>\r\n");
      out.write("    <script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyAkeLMlsiwzp6b3Gnaxd86lvakimwGA6UA&callback=initMap\"></script>    \r\n");
      out.write("    \r\n");
      out.write("    <script src=\"./front-end/js/script.js\"></script>\r\n");
      out.write("    <script src=\"./front-end/js/contact.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
