/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-04-09 09:13:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Map;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

if (session.getAttribute("user-email") != null) {
	response.sendRedirect("dashbord.jsp");
}

String successMessage = (String) session.getAttribute("forgot-password-success");
if (successMessage != null) {
	session.removeAttribute("forgot-password-success");
}

Map<String, String> fieldErrors = (Map<String, String>) session.getAttribute("fieldErrors");
String emailError = (fieldErrors != null && fieldErrors.containsKey("email")) ? fieldErrors.get("email")
		: null;
String passwordError = (fieldErrors != null && fieldErrors.containsKey("password")) ? fieldErrors.get("password")
		: null;
session.removeAttribute("fieldErrors");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <meta\r\n");
      out.write("      name=\"viewport\"\r\n");
      out.write("      content=\"width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0\"\r\n");
      out.write("    />\r\n");
      out.write("\r\n");
      out.write("    <title>ABC Laboratories</title>\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"description\" content=\"\" />\r\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"./back-end/assets/img/favicon/favicon.ico\" />\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./back-end/assets/vendor/fonts/boxicons.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./back-end/assets/vendor/css/core.css\" class=\"template-customizer-core-css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./back-end/assets/vendor/css/theme-default.css\" class=\"template-customizer-theme-css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./back-end/assets/css/demo.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./back-end/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./back-end/assets/vendor/css/pages/page-auth.css\" />\r\n");
      out.write("    <script src=\"./back-end/assets/vendor/js/helpers.js\"></script>\r\n");
      out.write("    <script src=\"./back-end/assets/js/config.js\"></script>\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"container-xxl\">\r\n");
      out.write("      <div class=\"authentication-wrapper authentication-basic container-p-y\">\r\n");
      out.write("        <div class=\"authentication-inner\">\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <div class=\"app-brand justify-content-center\">\r\n");
      out.write("                <a href=\"index.jsp\" class=\"app-brand-link gap-2\">\r\n");
      out.write("                  <span class=\"app-brand-text demo text-body fw-bolder\">ABC Laboratories</span>\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <h4 class=\"mb-2\">Welcome to ABC Laboratories!</h4>\r\n");
      out.write("              <p class=\"mb-4\">Please sign-in to your account and start the adventure</p>\r\n");
      out.write("							");

							if (successMessage != null) {
							
      out.write("\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"align-items-center justify-content-center text-center border border-success py-2 my-3\">\r\n");
      out.write("								<span class=\"text-success font-weight-bold\">");
      out.print(successMessage);
      out.write("</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							");

							}
							
      out.write("\r\n");
      out.write("              <form id=\"formAuthentication\" class=\"mb-3\" action=\"login\" method=\"POST\">\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label for=\"email\" class=\"form-label\">Email</label>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                      <input type=\"text\" class=\"form-control\" id=\"email\" name=\"email\" placeholder=\"Enter your email\" autofocus />\r\n");
      out.write("                      ");

                      if (emailError != null) {
                      
      out.write("\r\n");
      out.write("                      <span style=\"color: red;\">");
      out.print(emailError);
      out.write("</span>\r\n");
      out.write("                      ");

                      }
                      
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-3 form-password-toggle\">\r\n");
      out.write("                    <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                        <label class=\"form-label\" for=\"password\">Password</label>\r\n");
      out.write("                        <a href=\"forgotPassword.jsp\">\r\n");
      out.write("                            <small>Forgot Password?</small>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                    <div class=\"input-group input-group-merge\">\r\n");
      out.write("                        <input\r\n");
      out.write("                            type=\"password\"\r\n");
      out.write("                            id=\"password\"\r\n");
      out.write("                            class=\"form-control\"\r\n");
      out.write("                            name=\"password\"\r\n");
      out.write("                            placeholder=\"&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;\"\r\n");
      out.write("                            aria-describedby=\"password\"\r\n");
      out.write("                        />\r\n");
      out.write("                        <span class=\"input-group-text cursor-pointer\"><i class=\"bx bx-hide\"></i></span>\r\n");
      out.write("                      \r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");

                    if (passwordError != null) {
                    
      out.write("\r\n");
      out.write("                    <span style=\"color: red;\">");
      out.print(passwordError);
      out.write("</span>\r\n");
      out.write("                    ");

                    }
                    
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" id=\"remember-me\" />\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"remember-me\"> Remember Me </label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <button class=\"btn btn-primary d-grid w-100\" type=\"submit\">Sign in</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>            \r\n");
      out.write("\r\n");
      out.write("              <p class=\"text-center\">\r\n");
      out.write("                <span>New on our platform?</span>\r\n");
      out.write("                <a href=\"registration.jsp\">\r\n");
      out.write("                  <span>Create an account</span>\r\n");
      out.write("                </a>\r\n");
      out.write("              </p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./back-end/assets/vendor/libs/jquery/jquery.js\"></script>\r\n");
      out.write("    <script src=\"./back-end/assets/vendor/libs/popper/popper.js\"></script>\r\n");
      out.write("    <script src=\"./back-end/assets/vendor/js/bootstrap.js\"></script>\r\n");
      out.write("    <script src=\"./back-end/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js\"></script>\r\n");
      out.write("    <script src=\"./back-end/assets/js/jquery.validate.min.js\"></script>\r\n");
      out.write("    <script src=\"./back-end/assets/js/jquery.validate-init.js\"></script>\r\n");
      out.write("    <script src=\"./back-end/assets/vendor/js/menu.js\"></script>\r\n");
      out.write("    <script src=\"./back-end/assets/js/main.js\"></script>\r\n");
      out.write("    <script async defer src=\"https://buttons.github.io/buttons.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
